DECLARE
	CURSOR C1 IS
		SELECT EMPNO, ENAME, JOB, DEPTNO
		FROM EMP
		WHERE JOB = 'MANAGER';

	
	C2 C1%ROWTYPE;

BEGIN
	
	FOR C2 IN C1 LOOP
			DBMS_OUTPUT.PUT_LINE(C2.EMPNO||'		'||C2.ENAME||'		'||C2.JOB||'		'||C2.DEPTNO);
	END LOOP;

END;
/