--  직무: MANAGER인 사원의 사번, 이름, JOB, 부서번호 출력 

DECLARE
	CURSOR C1 IS
	SELECT EMPNO, ENAME, JOB, DEPTNO
	FROM EMP
	WHERE JOB = 'MANAGER';

	C2 C1%ROWTYPE;


BEGIN
	OPEN C1;

		IF C1%ISOPEN THEN
			DBMS_OUTPUT.PUT_LINE('OPEN 성공');
		END IF;

		LOOP
			FETCH C1 INTO C2;
			IF C1%FOUND THEN
				DBMS_OUTPUT.PUT_LINE('FETCH 성공');
			END IF;

			IF C1%NOTFOUND THEN
				DBMS_OUTPUT.PUT_LINE('FETCH 실패');
			END IF;

	-- TRUE가되면 LOOP문 탈출
	EXIT WHEN C1%NOTFOUND;

	-- 출력
	DBMS_OUTPUT.PUT_LINE(C1%ROWCOUNT||'번째 데이터	'||C2.EMPNO||'		'||C2.ENAME||'		'||C2.JOB||'	'||C2.DEPTNO);

	END LOOP;

	CLOSE C1;
END;
/