CREATE OR REPLACE PACKAGE BODY MY_PACK2

IS

	 FUNCTION GET_EVL_SAL (VEMPNO EMP.EMPNO%TYPE)
		RETURN NUMBER
	IS
		VAVGSAL NUMBER(10) := 0;
		VSAL NUMBER(10) := 0;
	BEGIN
		SELECT AVG(SAL)
			INTO VAVGSAL
		FROM EMP
		WHERE DEPTNO =(SELECT DEPTNO FROM EMP WHERE EMPNO = VEMPNO);

		SELECT SAL
			INTO VSAL
		FROM EMP
		WHERE EMPNO = VEMPNO;

		IF VSAL >= VAVGSAL THEN 
			RETURN VSAL;
		ELSE
			RETURN VAVGSAL ;
		END IF;
	END GET_EVL_SAL;


	PROCEDURE RAISE_SAL (VEMPNO EMP.EMPNO%TYPE, VRATIO NUMBER)

	IS

	BEGIN
		UPDATE EMP
		SET SAL = SAL*(1+VRATIO/100)
		WHERE EMPNO = VEMPNO;

	END RAISE_SAL;



	PROCEDURE DOWN_SAL (VEMPNO EMP.EMPNO%TYPE, VRATIO NUMBER)

	IS

	BEGIN
		UPDATE EMP
		SET SAL = SAL*(1-VRATIO/100)
		WHERE EMPNO = VEMPNO;

	END DOWN_SAL;





	PROCEDURE LOTTO_SAL (VEMPNO EMP.EMPNO%TYPE, VRATIO NUMBER)
	IS
		NUM  NUMBER := 0;

	BEGIN

		NUM := ROUND(DBMS_RANDOM.VALUE(1,10));

		IF  NUM = 1 OR NUM = 3 OR NUM = 7 THEN
			RAISE_SAL(VEMPNO, VRATIO);
			DBMS_OUTPUT.PUT_LINE('±Þ¿©»ó½Â');

		ELSIF NUM = 2 OR NUM = 4 OR NUM = 8 THEN
			DOWN_SAL(VEMPNO, VRATIO);
			DBMS_OUTPUT.PUT_LINE('±Þ¿©ÇÏ¶ô');
		ELSE 
			DBMS_OUTPUT.PUT_LINE('²Î');
		END IF;
	END LOTTO_SAL;
	




END;
/

