CREATE OR REPLACE PROCEDURE UPDATE_PHONE (VEMPNO EMP.EMPNO%TYPE)

IS
	VENAME NEW_EMP.ENAME%TYPE;
	VMP NEW_EMP.MP%TYPE;

BEGIN

	SELECT ENAME, MP
		INTO VENAME, VMP
	FROM NEW_EMP
	WHERE EMPNO = VEMPNO;

	IF SUBSTR(VMP, 1,3) IN (010) THEN
		UPDATE NEW_EMP
		SET MP = SUBSTR(VMP, 1,3)||'-'|| SUBSTR(VMP, 4,4)|| '-'||SUBSTR(VMP, 8,4)
		WHERE EMPNO = VEMPNO;
	ELSIF SUBSTR(VMP, 1,3) IN (031) THEN
		UPDATE NEW_EMP
		SET MP = SUBSTR(VMP, 1,3)||')'|| SUBSTR(VMP, 4,4)|| '-'||SUBSTR(VMP, 8,4)
		WHERE EMPNO = VEMPNO;
	ELSIF SUBSTR(VMP, 1,2) IN(02) THEN
		UPDATE NEW_EMP
		SET MP = SUBSTR(VMP, 1,2)||')'|| SUBSTR(VMP, 3,4)|| '-'||SUBSTR(VMP, 7,4)
		WHERE EMPNO = VEMPNO;
	END IF;
		
END;
/

