CREATE OR REPLACE FUNCTION FIND_DNAME (VEMPNO EMP.EMPNO%TYPE, )
	RETURN DEPT.DNAME%TYPE
IS
	VDNAME DEPT.DNAME%TYPE;

BEGIN
	SELECT DNAME
		INTO VDNAME
	FROM EMP E, DEPT D
	WHERE E.DEPTNO = D.DEPTNO AND E.EMPNO = VEMPNO;

	RETURN VDNAME;

END;
/