CREATE OR REPLACE PACKAGE MY_PACK2

IS
	--	PACKAGE SPEC
	-- 패키지에 쓸 함수 정의
	FUNCTION GET_EVL_SAL (VEMPNO EMP.EMPNO%TYPE)
	RETURN NUMBER;

	PROCEDURE RAISE_SAL (VEMPNO EMP.EMPNO%TYPE, VRATIO NUMBER);
	PROCEDURE DOWN_SAL (VEMPNO EMP.EMPNO%TYPE, VRATIO NUMBER);
	PROCEDURE LOTTO_SAL (VEMPNO EMP.EMPNO%TYPE, VRATIO NUMBER);


END;
/