DECLARE 
	VSCORE NUMBER := 70;

BEGIN
	-- 조건 분기문
	IF VSCORE >= 90 THEN
		DBMS_OUTPUT.PUT_LINE('A');
		DBMS_OUTPUT.PUT_LINE('^^');
	ELSIF VSCORE >= 80 THEN
		DBMS_OUTPUT.PUT_LINE('B');
	ELSIF VSCORE >= 70 THEN
		DBMS_OUTPUT.PUT_LINE('C');
	ELSIF VSCORE >= 60 THEN
		DBMS_OUTPUT.PUT_LINE('D');
	ELSE
		DBMS_OUTPUT.PUT_LINE('F');
	END IF;

END;
/