ACCEPT VNO PROMPT '사번입력:'

DECLARE
	VEMPNO NUMBER := &VNO;
	VENAME VARCHAR2(20);
	VSAL NUMBER;


BEGIN
	SELECT empno, ename,  sal
		INTO VEMPNO, VENAME, VSAL
	FROM emp
	WHERE empno = VEMPNO;
	DBMS_OUTPUT.PUT_LINE(VEMPNO||'		'||VENAME||'		'||VSAL);
END;
/