-- 사원번호
-- 사원명 job, sal, deptno

ACCEPT VNO PROMPT '사원번호: :'

DECLARE
	VEMPNO			EMP.EMPNO%TYPE :=  &VNO;
	VENAME			EMP.ENAME%TYPE;
	VJOB				EMP.JOB%TYPE;
	VMGR				EMP.MGR%TYPE;
	VHIREDATE		EMP.HIREDATE%TYPE;
	VSAL				EMP.SAL%TYPE;
	VCOMM			EMP.COMM%TYPE;
	VDEPTNO		EMP.DEPTNO%TYPE;



BEGIN
	SELECT *
		INTO VEMPNO, VENAME, VJOB, VMGR, VHIREDATE, VSAL, VCOMM, VDEPTNO 
	FROM EMP
	WHERE EMPNO = VEMPNO;
	DBMS_OUTPUT.PUT_LINE(VENAME||'		'||VJOB||'		'||VSAL||'		'||VDEPTNO);
END;
/