
ACCEPT VNO PROMPT '부서번호: :'

DECLARE
	VDEPT DEPT%ROWTYPE;

BEGIN
	SELECT *
		INTO VDEPT
	FROM DEPT
	WHERE DEPTNO = &VNO;
	DBMS_OUTPUT.PUT_LINE(VDEPT.DEPTNO||'		'||VDEPT.DNAME||'		'||VDEPT.LOC);
END;
/