DECLARE
	-- 같은 타입의 연속된 공간에 할당되는 변수
	-- PL/SQL은 배열을 PL/SQL 테이블이라고함. PL_SQL TABLE: PL_TAB
	-- TYPE PL_TAB IS TABLE OF 자료형

	TYPE PL_TAB IS TABLE OF EMP.ENAME%TYPE
	INDEX BY BINARY_INTEGER;

	-- String[] pl1 = new Stirng[10];

	PL1 PL_TAB;


BEGIN
	FOR i IN 1..20 LOOP
		PL1(I) := 'SCOTT' || i;
	END LOOP;

	FOR j IN 1..20 LOOP
		DBMS_OUTPUT.PUT_LINE(PL1(j));
	END LOOP;
END;
/