DECLARE
	-- 1. CURSOR 선언
	CURSOR C1 IS
	SELECT EMPNO, ENAME, SAL
	FROM EMP
	WHERE DEPTNO = 10;

	VEMPNO EMP.EMPNO%TYPE; 
	VENAME EMP.ENAME%TYPE; 
	VSAL EMP.SAL%TYPE;

	-- 변수가 많으면 ROWTYPE으로 선언한다.
	C2 C1%ROWTYPE;

BEGIN
	-- 2, OPEN
	OPEN C1;

	-- 3. FETCH

	--FETCH C1 INTO VEMPNO, VENAME, VSAL;
	--DBMS_OUTPUT.PUT_LINE(VEMPNO||'	'||VENAME||'	'||VSAL);

	LOOP
		FETCH C1 INTO C2;
		-- 더 이상 패치 할것이 없을때까지 반복
	EXIT WHEN  C1%NOTFOUND;
		DBMS_OUTPUT.PUT_LINE(C2.EMPNO||'	'||C2.ENAME||'	'||C2.SAL);
	END LOOP;

	-- 4. CLOSE
	CLOSE C1;

END;
/