DECLARE
	CURSOR C1 IS
	SELECT EMPNO, ENAME, SAL
	FROM EMP
	WHERE DEPTNO = 10;

	C2 C1%ROWTYPE;


BEGIN
	OPEN C1;

		IF C1%ISOPEN THEN
			DBMS_OUTPUT.PUT_LINE('OPEN 성공');
		END IF;

	LOOP
		FETCH C1 INTO C2;
		IF C1%FOUND THEN
			DBMS_OUTPUT.PUT_LINE('FETCH 성공');
		END IF;

		IF C1%NOTFOUND THEN
			DBMS_OUTPUT.PUT_LINE('FETCH 실패');
		END IF;

		-- TRUE가되면 LOOP문 탈출
		EXIT WHEN C1%NOTFOUND;

		-- 출력
		DBMS_OUTPUT.PUT_LINE(C1%ROWCOUNT||'번째 데이터	'||C2.EMPNO||'		'||C2.ENAME||'		'||C2.SAL);

	END LOOP;

	CLOSE C1;
END;
/