CREATE OR REPLACE FUNCTION ANNSAL (VEMPNO EMP.EMPNO%TYPE)
	RETURN NUMBER
IS
	VANNSAL NUMBER(10) := 0;

BEGIN
	SELECT SAL * 12 + NVL(COMM, 0)
		INTO VANNSAL
	FROM EMP
	WHERE EMPNO = VEMPNO;

	RETURN VANNSAL;

END;
/